import { useEffect, useMemo, useRef, useState } from 'react';
import type { Kdbx } from 'kdbxweb';
import { createTarget, type Target } from './domain/targets';
import { db } from './storage/db';
import { createVault, saveVault, unlockVault } from './vault/vault';
import { addEntry, addKey, getWorkspace, initializeWorkspace, type EncryptedWorkspace } from './vault/workspace';
import { serializeKeyStoreBackup } from './portability/backup';
import './app.css';
import './responsive.css';

const emptyWorkspace: EncryptedWorkspace = { entries: [], groups: [], tags: [], keys: [] };

export default function App() {
  const vaultRef = useRef<Kdbx | null>(null); const passwordRef = useRef<string>('');
  const [hasVault, setHasVault] = useState(false); const [workspace, setWorkspace] = useState(emptyWorkspace); const [locked, setLocked] = useState(true); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [editor, setEditor] = useState(false); const [showKeys, setShowKeys] = useState(false);
  useEffect(() => { void db.vaults.get('primary').then((record) => setHasVault(Boolean(record))); }, []);
  const refresh = () => { if (vaultRef.current) setWorkspace(getWorkspace(vaultRef.current)); };
  const persist = async () => { const vault = vaultRef.current; if (!vault) throw new Error('密钥库已锁定'); const data = await saveVault(vault, passwordRef.current); await db.vaults.put({ id: 'primary', data, updatedAt: new Date().toISOString() }); refresh(); };
  const open = async (create: boolean) => { try { setError(''); if (create && password !== confirm) return setError('两次输入的主密码不一致。'); const record = await db.vaults.get('primary'); const data = create ? await createVault(password) : record?.data; if (!data) return setError('找不到密钥库。'); const vault = await unlockVault(data, password); initializeWorkspace(vault); vaultRef.current = vault; passwordRef.current = password; if (create) await persist(); setWorkspace(getWorkspace(vault)); setLocked(false); setPassword(''); setConfirm(''); } catch { setError('无法打开密钥库，请检查主密码。'); } };
  const lock = () => { vaultRef.current = null; passwordRef.current = ''; setWorkspace(emptyWorkspace); setLocked(true); };
  const downloadBackup = async () => { const vault = vaultRef.current; if (!vault) return; const text = await serializeKeyStoreBackup(await saveVault(vault, passwordRef.current), passwordRef.current); const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = `linkmark-backup-${new Date().toISOString().slice(0, 10)}.txt`; link.click(); URL.revokeObjectURL(url); };
  const visible = useMemo(() => workspace.entries.filter((entry) => `${entry.name} ${Object.values(entry.config).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [workspace.entries, query]);
  if (locked) return <main className="lock-screen"><section className="lock-card"><div className="brand"><span>✦</span> Linkmark</div><p className="eyebrow">ENCRYPTED LOCAL WORKSPACE</p><h1>{hasVault ? '解锁密钥库' : '创建密钥库'}</h1><p>入口、密钥和全部组织信息均经过本机加密。解锁前不会显示任何资料。</p><label>主密码<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoFocus /></label>{!hasVault && <label>确认主密码<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>}{error && <p className="error">{error}</p>}<button className="primary" disabled={!password || (!hasVault && !confirm)} onClick={() => void open(!hasVault)}>{hasVault ? '解锁密钥库' : '创建密钥库'}</button><button className="text-button">导入加密包</button></section></main>;
  return <main className="shell"><aside className="sidebar"><div className="brand"><span>✦</span> Linkmark</div><button className="new-button" onClick={() => setEditor(true)}>＋ 新建入口</button><nav><button className="active">所有入口 <small>{workspace.entries.length}</small></button><button onClick={() => setShowKeys(!showKeys)}>密钥 <small>{workspace.keys.length}</small></button></nav><div className="sidebar-footer"><span className="lock-dot unlocked" />密钥库已解锁 <button onClick={lock}>锁定</button></div></aside><section className="content"><header><div><p className="eyebrow">ENCRYPTED LOCAL WORKSPACE</p><h1>{showKeys ? '密钥库' : '所有入口'}</h1></div><div className="actions"><button onClick={() => void downloadBackup()}>导出备份</button><button onClick={lock}>锁定密钥库</button></div></header>{showKeys ? <section className="vault-list"><h2>密钥</h2>{workspace.keys.length ? workspace.keys.map((key) => <div key={key.id}><span>{key.title}</span><small>{key.username || '未填写账号'}</small></div>) : <p>尚未创建密钥。</p>}</section> : <><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索入口、主机或地址…" /></label><div className="toolbar"><span>{visible.length} 个入口</span><button onClick={() => setEditor(true)}>新建入口</button></div>{visible.length ? <div className="grid">{visible.map((entry) => <article className="card" key={entry.id}><div className={`kind kind-${entry.kind}`}>{entry.kind === 'web' ? '↗' : '◆'}</div><div className="card-body"><p className="kind-label">{entry.kind}</p><h2>{entry.name}</h2><p>{Object.values(entry.config).join(' · ')}</p></div><div className="card-actions"><span className="link-secret">关联 {entry.vaultItemIds.length} 把密钥</span></div></article>)}</div> : <div className="empty"><span>✦</span><h2>建立你的第一个入口</h2><p>每一项资料都会保存到本机加密密钥库。</p><button onClick={() => setEditor(true)}>新建入口</button></div>}</>}{editor && <EntryEditor keys={workspace.keys} onClose={() => setEditor(false)} onSave={async (name, url, keyTitle, keyValue, existingIds) => { const vault = vaultRef.current!; const keyIds = [...existingIds, ...(keyTitle ? [addKey(vault, { title: keyTitle, password: keyValue })] : [])]; addEntry(vault, createTarget({ name, kind: 'web', config: { url }, vaultItemIds: keyIds })); await persist(); setEditor(false); }} />}</section></main>;
}

function EntryEditor({ keys, onClose, onSave }: { keys: EncryptedWorkspace['keys']; onClose: () => void; onSave: (name: string, url: string, keyTitle: string, keyValue: string, existingIds: string[]) => Promise<void> }) {
  const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [keyTitle, setKeyTitle] = useState(''); const [keyValue, setKeyValue] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState('');
  const submit = async () => { if (!name.trim() || !/^https?:\/\//.test(url)) return setError('请填写名称和 HTTP(S) 地址。'); await onSave(name.trim(), url, keyTitle.trim(), keyValue, selected); };
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="新建入口"><div className="modal-heading"><div><p className="eyebrow">NEW ENTRY</p><h2>新建入口</h2></div><button onClick={onClose}>×</button></div><label>名称<input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label><label>网站地址<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com" /></label>{keys.length > 0 && <fieldset><legend>关联已有密钥</legend>{keys.map((key) => <label className="checkbox" key={key.id}><input type="checkbox" checked={selected.includes(key.id)} onChange={() => setSelected((ids) => ids.includes(key.id) ? ids.filter((id) => id !== key.id) : [...ids, key.id])} />{key.title}{key.username && ` · ${key.username}`}</label>)}</fieldset>}<fieldset><legend>新建并关联密钥（可选）</legend><label>密钥名称<input value={keyTitle} onChange={(event) => setKeyTitle(event.target.value)} placeholder={name || '例如：生产账号'} /></label><label>密钥值<input type="password" value={keyValue} onChange={(event) => setKeyValue(event.target.value)} /></label></fieldset>{error && <p className="error">{error}</p>}<div className="modal-actions"><button onClick={onClose}>取消</button><button className="primary" onClick={() => void submit()}>保存入口</button></div></section></div>;
}
