import { useEffect, useMemo, useRef, useState } from 'react';
import type { Kdbx } from 'kdbxweb';
import { createTarget, validateTargetConfig, type Target, type TargetKind } from './domain/targets';
import { db, type Group, type Tag } from './storage/db';
import { createVault, rekeyVault, saveVault, unlockVault } from './vault/vault';
import { addEntry, addKey, deleteEntry, deleteKey, deleteWorkspaceGroup, deleteWorkspaceTag, emptyRecycledRecords, getKey, getWorkspace, initializeWorkspace, listRecycledRecords, mergeWorkspace, permanentlyDeleteRecycledRecord, purgeExpiredRecycledRecords, restoreRecycledRecord, setWorkspaceMetadata, updateEntry, updateKey, type EncryptedWorkspace, type RecycledRecord } from './vault/workspace';
import { parseKeyStoreBackup, serializeKeyStoreBackup } from './portability/backup';
import './app.css';
import './responsive.css';

const emptyWorkspace: EncryptedWorkspace = { entries: [], groups: [], tags: [], keys: [] };
const durations = [[300_000, '5 分钟'], [1_800_000, '30 分钟'], [7_200_000, '2 小时'], [86_400_000, '24 小时'], [604_800_000, '7 天']] as const;
const kindNames: Record<TargetKind, string> = { web: '网站', postgresql: 'PostgreSQL', redis: 'Redis', generic: '通用' };

export default function App() {
  const vaultRef = useRef<Kdbx | null>(null); const passwordRef = useRef('');
  const [hasVault, setHasVault] = useState(false); const [workspace, setWorkspace] = useState(emptyWorkspace); const [locked, setLocked] = useState(true); const [theme, setTheme] = useState<'dark' | 'light'>(() => localStorage.getItem('linkmark-theme') === 'light' ? 'light' : 'dark');
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [duration, setDuration] = useState(300_000); const [expiry, setExpiry] = useState<number | null>(null);
  const [query, setQuery] = useState(''); const [activeGroup, setActiveGroup] = useState<string | null | undefined>(undefined); const [view, setView] = useState<'entries' | 'keys'>('entries'); const [sortBy, setSortBy] = useState<'manual' | 'name' | 'updated'>('manual');
  const [entryEditor, setEntryEditor] = useState<Target | 'new' | null>(null); const [keyEditor, setKeyEditor] = useState<string | 'new' | null>(null); const [groupEditor, setGroupEditor] = useState(false); const [recycleOpen, setRecycleOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [shareOpen, setShareOpen] = useState(false);
  useEffect(() => { void db.vaults.get('primary').then((record) => setHasVault(Boolean(record))); }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('linkmark-theme', theme); }, [theme]);
  const refresh = () => { if (vaultRef.current) setWorkspace(getWorkspace(vaultRef.current)); };
  const persist = async () => { const vault = vaultRef.current; if (!vault) throw new Error('密钥库已锁定'); purgeExpiredRecycledRecords(vault); const data = await saveVault(vault, passwordRef.current); await db.vaults.put({ id: 'primary', data, updatedAt: new Date().toISOString() }); refresh(); };
  const lock = () => { vaultRef.current = null; passwordRef.current = ''; setWorkspace(emptyWorkspace); setExpiry(null); setLocked(true); setView('entries'); setEntryEditor(null); setKeyEditor(null); };
  useEffect(() => { window.addEventListener('pagehide', lock); return () => window.removeEventListener('pagehide', lock); }, []);
  useEffect(() => { if (!expiry) return; const timer = window.setTimeout(lock, Math.max(0, expiry - Date.now())); return () => window.clearTimeout(timer); }, [expiry]);
  const open = async (create: boolean) => { try {
    setError(''); if (create && password !== confirm) return setError('两次输入的主密码不一致。');
    const source = create ? await createVault(password) : (await db.vaults.get('primary'))?.data;
    if (!source) return setError('找不到密钥库。'); const vault = await unlockVault(source, password); initializeWorkspace(vault);
    vaultRef.current = vault; passwordRef.current = password; if (create) await persist(); else refresh(); setExpiry(Date.now() + duration); setLocked(false); setPassword(''); setConfirm('');
  } catch { setError('无法打开密钥库，请检查主密码。'); } };
  const importBackup = async (encoded: string, packagePassword: string, localPassword: string, mode: 'replace' | 'merge' = 'replace') => {
    const backup = await parseKeyStoreBackup(encoded, packagePassword); const vault = await unlockVault(backup.vault, packagePassword); initializeWorkspace(vault);
    if (mode === 'merge' && vaultRef.current) {
      const current = vaultRef.current; const snapshot = await saveVault(current, passwordRef.current);
      try { mergeWorkspace(current, vault); await persist(); setImportOpen(false); } catch (cause) { vaultRef.current = await unlockVault(snapshot, passwordRef.current); refresh(); throw cause; }
      return;
    }
    vaultRef.current = vault; passwordRef.current = localPassword; await persist(); setWorkspace(getWorkspace(vault)); setExpiry(Date.now() + duration); setHasVault(true); setLocked(false); setImportOpen(false);
  };
  const downloadBackup = async () => { const vault = vaultRef.current; if (!vault) return; const text = await serializeKeyStoreBackup(await saveVault(vault, passwordRef.current), passwordRef.current); download(text, 'linkmark-backup'); };
  const visible = useMemo(() => workspace.entries.filter((entry) => {
    if (activeGroup !== undefined && entry.groupId !== activeGroup) return false;
    const keys = entry.vaultItemIds.map((id) => workspace.keys.find((key) => key.id === id)).filter(Boolean).map((key) => `${key!.title} ${key!.username}`).join(' ');
    const tags = entry.tagIds.map((id) => workspace.tags.find((tag) => tag.id === id)?.name ?? '').join(' ');
    return `${entry.name} ${Object.values(entry.config).join(' ')} ${keys} ${tags}`.toLowerCase().includes(query.toLowerCase());
  }).sort((a, b) => sortBy === 'name' ? a.name.localeCompare(b.name, 'zh-CN') : sortBy === 'updated' ? b.updatedAt.localeCompare(a.updatedAt) : Number(b.pinned) - Number(a.pinned) || a.sortOrder - b.sortOrder), [workspace, query, activeGroup, sortBy]);
  if (locked) return <LockScreen hasVault={hasVault} password={password} confirm={confirm} duration={duration} error={error} onPassword={setPassword} onConfirm={setConfirm} onDuration={setDuration} onOpen={() => void open(!hasVault)} onImport={() => setImportOpen(true)} importOpen={importOpen} onCloseImport={() => setImportOpen(false)} onImportBackup={importBackup} />;
  const addGroup = async (name: string) => { if (!vaultRef.current) return; setWorkspaceMetadata(vaultRef.current, { groups: [...workspace.groups, { id: crypto.randomUUID(), name, sortOrder: workspace.groups.length }], tags: workspace.tags }); await persist(); };
  const addTag = async (name: string) => { if (!vaultRef.current) return; setWorkspaceMetadata(vaultRef.current, { groups: workspace.groups, tags: [...workspace.tags, { id: crypto.randomUUID(), name }] }); await persist(); };
  return <main className="shell"><aside className="sidebar"><div className="brand"><span>✦</span> Linkmark</div><button className="new-button" onClick={() => setEntryEditor('new')}>＋ 新建入口</button><nav>
    <button className={view === 'entries' && activeGroup === undefined ? 'active' : ''} onClick={() => { setView('entries'); setActiveGroup(undefined); }}>所有入口 <small>{workspace.entries.length}</small></button>
    <button className={view === 'entries' && activeGroup === null ? 'active' : ''} onClick={() => { setView('entries'); setActiveGroup(null); }}>默认分组</button>
    <div className="section-title">分组 <button aria-label="新建分组" onClick={() => setGroupEditor(true)}>＋</button></div>
    {workspace.groups.map((group) => <button className={view === 'entries' && activeGroup === group.id ? 'active' : ''} onClick={() => { setView('entries'); setActiveGroup(group.id); }} key={group.id}>{group.name}</button>)}
    <button className={view === 'keys' ? 'active' : ''} onClick={() => setView('keys')}>密钥 <small>{workspace.keys.length}</small></button>
  </nav><div className="sidebar-footer"><span className="lock-dot unlocked" />密钥库已解锁 <button onClick={lock}>锁定</button></div></aside>
  <section className="content"><header><div><p className="eyebrow">本机加密工作区</p><h1>{view === 'keys' ? '密钥库' : activeGroup === null ? '默认分组' : activeGroup ? workspace.groups.find((group) => group.id === activeGroup)?.name : '所有入口'}</h1></div><div className="actions"><button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? '浅色模式' : '深色模式'}</button><button onClick={() => setRecycleOpen(true)}>回收站</button><button onClick={() => setImportOpen(true)}>导入恢复</button><button onClick={() => setShareOpen(true)}>分享加密包</button><button onClick={() => void downloadBackup()}>导出备份</button><button onClick={lock}>锁定密钥库</button></div></header>
  {view === 'keys' ? <KeyList workspace={workspace} onNew={() => setKeyEditor('new')} onEdit={setKeyEditor} onDelete={async (key) => { if (window.confirm(`删除密钥“${key.title}”并解除所有入口关联？`)) { deleteKey(vaultRef.current!, key.id); await persist(); } }} /> : <EntryList visible={visible} query={query} sortBy={sortBy} onSort={setSortBy} onQuery={setQuery} tags={workspace.tags} onNew={() => setEntryEditor('new')} onEdit={setEntryEditor} onDelete={async (entry) => { if (window.confirm(`将“${entry.name}”移入回收站？`)) { deleteEntry(vaultRef.current!, entry.id); await persist(); } }} />}
  {entryEditor && <EntryEditor entry={entryEditor === 'new' ? undefined : entryEditor} keys={workspace.keys} groups={workspace.groups} tags={workspace.tags} onClose={() => setEntryEditor(null)} onSave={async (entry, createdKey) => { const vault = vaultRef.current!; const keyId = createdKey?.title ? addKey(vault, createdKey) : null; const next = { ...entry, vaultItemIds: [...entry.vaultItemIds, ...(keyId ? [keyId] : [])] }; if (entryEditor === 'new') addEntry(vault, next); else updateEntry(vault, next); await persist(); setEntryEditor(null); }} />}
  {keyEditor && <KeyEditor keyId={keyEditor === 'new' ? undefined : keyEditor} vault={vaultRef.current!} linkedEntries={workspace.entries.filter((entry) => entry.vaultItemIds.includes(keyEditor === 'new' ? '' : keyEditor))} onClose={() => setKeyEditor(null)} onSave={async (id, input) => { if (id) updateKey(vaultRef.current!, id, input); else addKey(vaultRef.current!, input); await persist(); setKeyEditor(null); }} />}
  {groupEditor && <GroupEditor groups={workspace.groups} tags={workspace.tags} onClose={() => setGroupEditor(false)} onSave={async (name) => { await addGroup(name); }} onAddTag={addTag} onDelete={async (id) => { deleteWorkspaceGroup(vaultRef.current!, id); if (activeGroup === id) setActiveGroup(undefined); await persist(); }} onDeleteTag={async (id) => { deleteWorkspaceTag(vaultRef.current!, id); await persist(); }} />}
  {recycleOpen && <RecycleDialog vault={vaultRef.current!} onClose={() => setRecycleOpen(false)} onChanged={persist} />}
  {importOpen && <ImportDialog hasVault onClose={() => setImportOpen(false)} onImport={importBackup} />}
  {shareOpen && <ShareDialog onClose={() => setShareOpen(false)} onShare={async (sharePassword) => { const source = await saveVault(vaultRef.current!, passwordRef.current); const rekeyed = await rekeyVault(source, passwordRef.current, sharePassword); return serializeKeyStoreBackup(rekeyed, sharePassword, 'share'); }} />}
  </section></main>;
}

function LockScreen(props: { hasVault: boolean; password: string; confirm: string; duration: number; error: string; onPassword: (value: string) => void; onConfirm: (value: string) => void; onDuration: (value: number) => void; onOpen: () => void; onImport: () => void; importOpen: boolean; onCloseImport: () => void; onImportBackup: (encoded: string, packagePassword: string, localPassword: string, mode?: 'replace' | 'merge') => Promise<void> }) {
  return <main className="lock-screen"><section className="lock-card"><div className="brand"><span>✦</span> Linkmark</div><p className="eyebrow">本机加密工作区</p><h1>{props.hasVault ? '解锁密钥库' : '创建密钥库'}</h1><p>入口、密钥和全部组织信息均经过本机加密。解锁前不会显示任何资料。</p><label>主密码<input type="password" value={props.password} onChange={(event) => props.onPassword(event.target.value)} autoFocus /></label>{!props.hasVault && <><label>确认主密码<input type="password" value={props.confirm} onChange={(event) => props.onConfirm(event.target.value)} /></label><p className="security-note">主密码无法找回；建议使用长口令，并妥善保留加密备份。</p></>}<label>免密时长<select value={props.duration} onChange={(event) => props.onDuration(Number(event.target.value))}>{durations.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{props.error && <p className="error">{props.error}</p>}<button className="primary" disabled={!props.password || (!props.hasVault && !props.confirm)} onClick={props.onOpen}>{props.hasVault ? '解锁密钥库' : '创建密钥库'}</button><button className="text-button" onClick={props.onImport}>{props.hasVault ? '替换恢复' : '导入加密包'}</button></section>{props.importOpen && <ImportDialog hasVault={props.hasVault} onClose={props.onCloseImport} onImport={props.onImportBackup} />}</main>;
}

function EntryList({ visible, query, sortBy, onSort, onQuery, tags, onNew, onEdit, onDelete }: { visible: Target[]; query: string; sortBy: 'manual' | 'name' | 'updated'; onSort: (sort: 'manual' | 'name' | 'updated') => void; onQuery: (value: string) => void; tags: Tag[]; onNew: () => void; onEdit: (entry: Target) => void; onDelete: (entry: Target) => Promise<void> }) {
 return <><label className="search"><span>⌕</span><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="搜索入口、分组、标签或密钥…" /></label><div className="toolbar"><span>{visible.length} 个入口</span><span className="sort-label">排序<select value={sortBy} onChange={(event) => onSort(event.target.value as 'manual' | 'name' | 'updated')}><option value="manual">手动顺序</option><option value="name">名称</option><option value="updated">最近更新</option></select></span><button onClick={onNew}>新建入口</button></div>{visible.length ? <div className="grid">{visible.map((entry) => <article className="card" key={entry.id}><div className={`kind kind-${entry.kind}`}>{entry.kind === 'web' ? '↗' : '◆'}</div><div className="card-body"><p className="kind-label">{kindNames[entry.kind]}</p><h2>{entry.name}</h2><p>{Object.values(entry.config).join(' · ')}</p></div><div className="card-tags">{entry.tagIds.map((id) => tags.find((tag) => tag.id === id)?.name).filter(Boolean).join(' · ')}</div><div className="card-actions"><span className="link-secret">关联 {entry.vaultItemIds.length} 把密钥</span>{entry.kind === 'web' && typeof entry.config.url === 'string' && <a href={entry.config.url} target="_blank" rel="noreferrer">打开</a>}<button onClick={() => onEdit(entry)}>编辑</button><button onClick={() => void onDelete(entry)}>删除</button></div></article>)}</div> : <div className="empty"><span>✦</span><h2>建立你的第一个入口</h2><p>每一项资料都会保存到本机加密密钥库。</p><button onClick={onNew}>新建入口</button></div>}</>;
}

function KeyList({ workspace, onNew, onEdit, onDelete }: { workspace: EncryptedWorkspace; onNew: () => void; onEdit: (id: string) => void; onDelete: (key: EncryptedWorkspace['keys'][number]) => Promise<void> }) {
 return <section className="vault-list"><h2>密钥 <button onClick={onNew}>新建密钥</button></h2>{workspace.keys.length ? workspace.keys.map((key) => <div key={key.id}><button className="vault-item" onClick={() => onEdit(key.id)}><strong>{key.title}</strong><small>{key.username || '未填写账号'} · 关联 {workspace.entries.filter((entry) => entry.vaultItemIds.includes(key.id)).length} 个入口</small></button><button onClick={() => void onDelete(key)}>删除</button></div>) : <p>尚未创建密钥。密钥可以被多个入口复用。</p>}</section>;
}

function EntryEditor({ entry, keys, groups, tags, onClose, onSave }: { entry?: Target; keys: EncryptedWorkspace['keys']; groups: Group[]; tags: Tag[]; onClose: () => void; onSave: (entry: Target, createdKey?: { title: string; username?: string; password?: string; notes?: string }) => Promise<void> }) {
  const [name, setName] = useState(entry?.name ?? ''); const [kind, setKind] = useState<TargetKind>(entry?.kind ?? 'web'); const [config, setConfig] = useState<Record<string, string | number | boolean>>(stringConfig(entry?.config)); const [groupId, setGroupId] = useState(entry?.groupId ?? ''); const [tagIds, setTagIds] = useState(entry?.tagIds ?? []); const [selected, setSelected] = useState(entry?.vaultItemIds ?? []); const [keyTitle, setKeyTitle] = useState(''); const [keyUser, setKeyUser] = useState(''); const [keyValue, setKeyValue] = useState(''); const [keyNotes, setKeyNotes] = useState(''); const [error, setError] = useState('');
  const setField = (field: string, value: string | boolean) => setConfig((current) => ({ ...current, [field]: value }));
  const submit = async () => { const cleaned = normalizeConfig(kind, config); if (!name.trim() || !validateTargetConfig(kind, cleaned)) return setError(kind === 'web' ? '请填写有效的 HTTP 或 HTTPS 网站地址。' : '请检查连接资料；账号、密码、DSN 和 Token 必须保存为密钥。'); if (keyValue && !keyTitle.trim()) return setError('新密钥需要填写名称。'); const base = entry ? { ...entry, name: name.trim(), kind, config: cleaned, groupId: groupId || null, tagIds, vaultItemIds: selected, updatedAt: new Date().toISOString() } : createTarget({ name, kind, config: cleaned, groupId: groupId || null, tagIds, vaultItemIds: selected }); await onSave(base, keyTitle.trim() ? { title: keyTitle.trim(), username: keyUser, password: keyValue, notes: keyNotes } : undefined); };
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={entry ? '编辑入口' : '新建入口'}><div className="modal-heading"><div><p className="eyebrow">入口资料</p><h2>{entry ? '编辑入口' : '新建入口'}</h2></div><button onClick={onClose}>×</button></div><label>名称<input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label><label>类型<select value={kind} onChange={(event) => { const next = event.target.value as TargetKind; setKind(next); setConfig(defaultConfig(next)); }}><option value="web">网站</option><option value="postgresql">PostgreSQL</option><option value="redis">Redis</option><option value="generic">通用</option></select></label><ConfigFields kind={kind} config={config} setField={setField} /><label>分组<select value={groupId} onChange={(event) => setGroupId(event.target.value)}><option value="">默认分组</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label>{tags.length > 0 && <fieldset><legend>标签</legend>{tags.map((tag) => <label className="checkbox" key={tag.id}><input type="checkbox" checked={tagIds.includes(tag.id)} onChange={() => setTagIds((ids) => ids.includes(tag.id) ? ids.filter((id) => id !== tag.id) : [...ids, tag.id])} />{tag.name}</label>)}</fieldset>}<fieldset><legend>关联已有密钥</legend>{keys.length ? keys.map((key) => <label className="checkbox" key={key.id}><input type="checkbox" checked={selected.includes(key.id)} onChange={() => setSelected((ids) => ids.includes(key.id) ? ids.filter((id) => id !== key.id) : [...ids, key.id])} />{key.title}{key.username && ` · ${key.username}`}</label>) : <p className="security-note">暂无密钥；可在下方直接创建并关联。</p>}</fieldset><fieldset><legend>新建并关联密钥（可选）</legend><label>密钥名称<input value={keyTitle} onChange={(event) => setKeyTitle(event.target.value)} placeholder={name || '例如：生产账号'} /></label><label>账号（可选）<input value={keyUser} onChange={(event) => setKeyUser(event.target.value)} /></label><label>密钥值<input type="password" value={keyValue} onChange={(event) => setKeyValue(event.target.value)} /></label><label>备注（可选）<textarea value={keyNotes} onChange={(event) => setKeyNotes(event.target.value)} /></label></fieldset>{error && <p className="error">{error}</p>}<div className="modal-actions"><button onClick={onClose}>取消</button><button className="primary" onClick={() => void submit()}>保存入口</button></div></section></div>;
}

function ConfigFields({ kind, config, setField }: { kind: TargetKind; config: Record<string, string | number | boolean>; setField: (key: string, value: string | boolean) => void }) {
 if (kind === 'web') return <label>网站地址<input value={String(config.url ?? '')} onChange={(event) => setField('url', event.target.value)} placeholder="https://example.com" /></label>;
 if (kind === 'generic') return <label>非敏感资料（每行：名称: 内容）<textarea value={String(config.details ?? '')} onChange={(event) => setField('details', event.target.value)} placeholder="区域: cn-north-1\n项目: 示例项目" /></label>;
 return <><label>主机<input value={String(config.host ?? '')} onChange={(event) => setField('host', event.target.value)} placeholder="db.example.com" /></label><label>端口<input inputMode="numeric" value={String(config.port ?? '')} onChange={(event) => setField('port', event.target.value)} placeholder={kind === 'postgresql' ? '5432' : '6379'} /></label><label>{kind === 'postgresql' ? '数据库' : '数据库编号'}<input value={String(config.database ?? '')} onChange={(event) => setField('database', event.target.value)} /></label>{kind === 'postgresql' ? <label>SSL 模式<select value={String(config.sslMode ?? 'prefer')} onChange={(event) => setField('sslMode', event.target.value)}>{['disable', 'prefer', 'require', 'verify-ca', 'verify-full'].map((mode) => <option key={mode}>{mode}</option>)}</select></label> : <label className="checkbox"><input type="checkbox" checked={Boolean(config.tls)} onChange={(event) => setField('tls', event.target.checked)} />使用 TLS</label>}</>;
}

function KeyEditor({ keyId, vault, linkedEntries, onClose, onSave }: { keyId?: string; vault: Kdbx; linkedEntries: Target[]; onClose: () => void; onSave: (id: string | undefined, input: { title: string; username?: string; password?: string; notes?: string; fields?: Record<string, string> }) => Promise<void> }) {
 const existing = keyId ? getKey(vault, keyId) : null; const [title, setTitle] = useState(existing?.title ?? ''); const [username, setUsername] = useState(existing?.username ?? ''); const [value, setValue] = useState(existing?.password ?? ''); const [notes, setNotes] = useState(existing?.notes ?? ''); const [fields, setFields] = useState(Object.entries(existing?.fields ?? {}).map(([name, value]) => `${name}: ${value}`).join('\n')); const [show, setShow] = useState(false);
 return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={keyId ? '编辑密钥' : '新建密钥'}><div className="modal-heading"><h2>{keyId ? '编辑密钥' : '新建密钥'}</h2><button onClick={onClose}>×</button></div><label>密钥名称<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>账号（可选）<input value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>密钥值（密码、API Key 或 Token）<div className="copy-field"><input type={show ? 'text' : 'password'} value={value} onChange={(event) => setValue(event.target.value)} /><button type="button" onClick={() => setShow(!show)}>{show ? '隐藏' : '显示'}</button>{keyId && <button type="button" onClick={() => void navigator.clipboard?.writeText(value)}>复制</button>}</div></label><label>备注（可选）<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><label>自定义字段（每行：名称: 值）<textarea value={fields} onChange={(event) => setFields(event.target.value)} /></label>{keyId && <p className="security-note">关联入口：{linkedEntries.length ? linkedEntries.map((entry) => entry.name).join('、') : '尚未关联'}</p>}<div className="modal-actions"><button onClick={onClose}>取消</button><button className="primary" disabled={!title.trim()} onClick={() => void onSave(keyId, { title: title.trim(), username, password: value, notes, fields: parseLines(fields) })}>保存密钥</button></div></section></div>;
}

function GroupEditor({ groups, tags, onClose, onSave, onAddTag, onDelete, onDeleteTag }: { groups: Group[]; tags: Tag[]; onClose: () => void; onSave: (name: string) => Promise<void>; onAddTag: (name: string) => Promise<void>; onDelete: (id: string) => Promise<void>; onDeleteTag: (id: string) => Promise<void> }) { const [name, setName] = useState(''); const [tag, setTag] = useState(''); return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="管理分组和标签"><div className="modal-heading"><h2>管理分组和标签</h2><button onClick={onClose}>×</button></div><label>新分组名称<input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label><div className="modal-actions"><button className="primary" disabled={!name.trim()} onClick={() => { void onSave(name.trim()); setName(''); }}>新建分组</button></div>{groups.map((group) => <div className="recycle-row" key={group.id}><span>{group.name}</span><button onClick={() => { if (window.confirm(`删除分组“${group.name}”？其中入口会移入默认分组。`)) void onDelete(group.id); }}>删除</button></div>)}<hr /><label>新标签名称<input value={tag} onChange={(event) => setTag(event.target.value)} /></label><div className="modal-actions"><button className="primary" disabled={!tag.trim()} onClick={() => { void onAddTag(tag.trim()); setTag(''); }}>新建标签</button></div>{tags.map((item) => <div className="recycle-row" key={item.id}><span>{item.name}</span><button onClick={() => { if (window.confirm(`删除标签“${item.name}”？它将从所有入口移除。`)) void onDeleteTag(item.id); }}>删除</button></div>)}<div className="modal-actions"><button onClick={onClose}>完成</button></div></section></div>; }

function RecycleDialog({ vault, onClose, onChanged }: { vault: Kdbx; onClose: () => void; onChanged: () => Promise<void> }) { const [records, setRecords] = useState<RecycledRecord[]>(() => listRecycledRecords(vault)); const refresh = async () => { await onChanged(); setRecords(listRecycledRecords(vault)); }; return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="回收站"><div className="modal-heading"><div><h2>回收站</h2><p className="security-note">删除的资料会在 30 天后自动永久清理。</p></div><button onClick={onClose}>×</button></div>{records.length ? <>{records.map((record) => <div className="recycle-row" key={record.id}><span><strong>{record.title}</strong><small>{record.kind === 'entry' ? '入口' : '密钥'}</small></span><button onClick={() => { restoreRecycledRecord(vault, record.id); void refresh(); }}>恢复</button><button onClick={() => { if (window.confirm('永久删除后无法恢复，是否继续？')) { permanentlyDeleteRecycledRecord(vault, record.id); void refresh(); } }}>永久删除</button></div>)}<div className="modal-actions"><button onClick={onClose}>关闭</button><button onClick={() => { if (window.confirm('清空回收站后无法恢复，是否继续？')) { emptyRecycledRecords(vault); void refresh(); } }}>清空回收站</button></div></> : <><p className="security-note">回收站为空。</p><div className="modal-actions"><button onClick={onClose}>关闭</button></div></>}</section></div>; }

function ImportDialog({ hasVault, onClose, onImport }: { hasVault: boolean; onClose: () => void; onImport: (encoded: string, packagePassword: string, localPassword: string, mode?: 'replace' | 'merge') => Promise<void> }) {
  const [encoded, setEncoded] = useState(''); const [packagePassword, setPackagePassword] = useState(''); const [localPassword, setLocalPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [mode, setMode] = useState<'replace' | 'merge'>('replace'); const [preview, setPreview] = useState<{ packageMode: 'backup' | 'share'; entries: number; keys: number; groups: number; tags: number } | null>(null); const [error, setError] = useState('');
  const inspect = async () => { try { const backup = await parseKeyStoreBackup(encoded.trim(), packagePassword); const vault = await unlockVault(backup.vault, packagePassword); initializeWorkspace(vault); const state = getWorkspace(vault); setPreview({ packageMode: backup.mode, entries: state.entries.length, keys: state.keys.length, groups: state.groups.length, tags: state.tags.length }); setError(''); } catch (cause) { setPreview(null); setError(cause instanceof Error ? cause.message : '无法读取加密包。'); } };
  const submit = async () => { if (!preview) return; if (mode === 'replace' && preview.packageMode === 'share' && (!localPassword || localPassword !== confirm)) return setError('请确认新的本地主密码。'); try { await onImport(encoded.trim(), packagePassword, preview.packageMode === 'share' ? localPassword : packagePassword, mode); } catch (cause) { setError(cause instanceof Error ? cause.message : '无法导入加密包。'); } };
  const resetPreview = () => setPreview(null);
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="导入加密包"><div className="modal-heading"><h2>导入加密包</h2><button onClick={onClose}>×</button></div>{hasVault && <label>导入方式<select value={mode} onChange={(event) => { setMode(event.target.value as 'replace' | 'merge'); resetPreview(); }}><option value="replace">恢复并替换当前密钥库</option><option value="merge">合并到当前密钥库</option></select></label>}<p className="security-note">{mode === 'merge' ? '合并会创建新副本，不会覆盖本地资料。' : hasVault ? '替换会清除当前全部资料；请先导出备份。' : '常规备份将继续使用备份主密码；分享包会要求设置新的本地主密码。'}</p><label>加密字符串<textarea value={encoded} onChange={(event) => { setEncoded(event.target.value); resetPreview(); }} /></label><label>备份或分享口令<input type="password" value={packagePassword} onChange={(event) => { setPackagePassword(event.target.value); resetPreview(); }} /></label>{preview?.packageMode === 'share' && mode === 'replace' && <><label>新的本地主密码<input type="password" value={localPassword} onChange={(event) => setLocalPassword(event.target.value)} /></label><label>确认新的本地主密码<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label></>}{preview && <p className="security-note">导入预览：{preview.entries} 个入口、{preview.keys} 把密钥、{preview.groups} 个分组、{preview.tags} 个标签。资料尚未写入本机。</p>}{error && <p className="error">{error}</p>}<div className="modal-actions"><button onClick={onClose}>取消</button>{preview ? <button className="primary" disabled={preview.packageMode === 'share' && mode === 'replace' && !localPassword} onClick={() => void submit()}>{mode === 'merge' ? '确认合并导入' : '确认恢复'}</button> : <button className="primary" disabled={!encoded || !packagePassword} onClick={() => void inspect()}>解密并预览</button>}</div></section></div>;
}

function ShareDialog({ onClose, onShare }: { onClose: () => void; onShare: (password: string) => Promise<string> }) { const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [result, setResult] = useState(''); const [error, setError] = useState(''); const create = async () => { if (!password || password !== confirm) return setError('请确认分享口令。'); try { const text = await onShare(password); setResult(text); await navigator.clipboard?.writeText(text); } catch { setError('无法创建或复制分享包。请检查浏览器剪贴板权限。'); } }; return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="分享加密包"><div className="modal-heading"><h2>分享加密包</h2><button onClick={onClose}>×</button></div><p className="security-note">分享包使用独立口令加密，接收方导入时会设置自己的本地主密码。</p>{result ? <><label>已生成的加密字符串<textarea readOnly value={result} /></label><p className="security-note">已尝试复制到剪贴板；如浏览器拒绝权限，请手动复制上方字符串。</p></> : <><label>分享口令<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>确认分享口令<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{error && <p className="error">{error}</p>}<div className="modal-actions"><button onClick={onClose}>取消</button><button className="primary" onClick={() => void create()}>生成并复制</button></div></>}<div className="modal-actions">{result && <button onClick={onClose}>完成</button>}</div></section></div>; }

const defaultConfig = (kind: TargetKind): Record<string, string | number | boolean> => kind === 'web' ? { url: '' } : kind === 'postgresql' ? { host: '', port: '5432', database: '', sslMode: 'prefer' } : kind === 'redis' ? { host: '', port: '6379', database: '0', tls: false } : { details: '' };
const stringConfig = (config: Target['config'] | undefined) => config ? Object.fromEntries(Object.entries(config).map(([key, value]) => [key, value])) : defaultConfig('web');
const normalizeConfig = (kind: TargetKind, config: Record<string, string | number | boolean>) => Object.fromEntries(Object.entries(config).map(([key, value]) => [key, typeof value === 'string' ? value.trim() : value])) as Target['config'];
const parseLines = (value: string) => Object.fromEntries(value.split('\n').flatMap((line) => { const separator = line.indexOf(':'); if (separator < 1 || !line.slice(separator + 1).trim()) return []; return [[line.slice(0, separator).trim(), line.slice(separator + 1).trim()]]; }));
function download(text: string, prefix: string) { const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = `${prefix}-${new Date().toISOString().slice(0, 10)}.txt`; link.click(); URL.revokeObjectURL(url); }
